CREATE TABLE subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_sub TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL,
    email_normalized TEXT NOT NULL UNIQUE,
    referrer_id BIGINT REFERENCES subscribers(id),
    invite_token TEXT NOT NULL UNIQUE,
    age_confirmed BOOLEAN NOT NULL CHECK (age_confirmed),
    consent_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_subscribers_referrer ON subscribers(referrer_id);
