-- 카카오톡 채널 버튼 클릭 기록. 실제 채널 추가 여부가 아니다. 등록자 파기 시 함께 삭제한다.
CREATE TABLE kakao_channel_clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscriber_id BIGINT NOT NULL REFERENCES subscribers(id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    clicked_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_kakao_channel_clicks_subscriber_source UNIQUE (subscriber_id, source)
);
